# Generated by Django 2.2 on 2019-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_callgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGraphNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='CallGraph',
            new_name='CallGraphEdge',
        ),
    ]
