# Generated by Django 2.2 on 2019-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20190511_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callgraphedge',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='callgraphedge',
            name='start',
            field=models.IntegerField(),
        ),
    ]
